{"totalCount":7,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/aides-territoires","vulnerabilityAlerts":{"totalCount":7,"nodes":[{"dismissedAt":null,"createdAt":"2023-12-21T20:24:53Z","securityVulnerability":{"severity":"HIGH","package":{"name":"scrapy"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h7wm-ph43-c39p"},{"type":"CVE","value":"CVE-2017-14158"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2017-14158"},{"url":"https://github.com/scrapy/scrapy/issues/482"},{"url":"http://blog.csdn.net/wangtua/article/details/75228728"},{"url":"https://github.com/pypa/advisory-database/blob/8b7a4d62a95e8f605e5dfb4e0b4f299e6403dc12/vulns/scrapy/PYSEC-2017-83.yaml"},{"url":"https://github.com/advisories/GHSA-h7wm-ph43-c39p"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/scrapy/PYSEC-2017-83.yaml"}]}}},{"dismissedAt":null,"createdAt":"2024-01-10T16:53:35Z","securityVulnerability":{"severity":"HIGH","package":{"name":"GitPython"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2mqj-m65w-jghx"},{"type":"CVE","value":"CVE-2024-22190"}],"references":[{"url":"https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-2mqj-m65w-jghx"},{"url":"https://github.com/gitpython-developers/GitPython/pull/1792"},{"url":"https://github.com/gitpython-developers/GitPython/commit/ef3192cc414f2fd9978908454f6fd95243784c7f"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-22190"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2024-4.yaml"},{"url":"https://github.com/advisories/GHSA-2mqj-m65w-jghx"}]}}},{"dismissedAt":null,"createdAt":"2024-01-22T22:00:52Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Pillow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-3f63-hfp8-52jq"},{"type":"CVE","value":"CVE-2023-50447"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-50447"},{"url":"https://devhub.checkmarx.com/cve-details/CVE-2023-50447/"},{"url":"https://duartecsantos.github.io/2023-01-02-CVE-2023-50447/"},{"url":"https://github.com/python-pillow/Pillow/commit/45c726fd4daa63236a8f3653530f297dc87b160a"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/10.2.0.html#security"},{"url":"http://www.openwall.com/lists/oss-security/2024/01/20/1"},{"url":"https://github.com/python-pillow/Pillow/releases"},{"url":"https://lists.debian.org/debian-lts-announce/2024/01/msg00019.html"},{"url":"https://github.com/advisories/GHSA-3f63-hfp8-52jq"}]}}},{"dismissedAt":null,"createdAt":"2024-01-30T00:02:32Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"aiohttp"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8qpw-xqxj-h4r2"},{"type":"CVE","value":"CVE-2024-23829"}],"references":[{"url":"https://github.com/aio-libs/aiohttp/security/advisories/GHSA-8qpw-xqxj-h4r2"},{"url":"https://github.com/aio-libs/aiohttp/security/advisories/GHSA-gfw2-4jvh-wgfg"},{"url":"https://github.com/aio-libs/aiohttp/pull/3235"},{"url":"https://github.com/aio-libs/aiohttp/pull/8074/files"},{"url":"https://github.com/aio-libs/aiohttp/commit/33ccdfb0a12690af5bb49bda2319ec0907fa7827"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-23829"},{"url":"https://github.com/aio-libs/aiohttp/pull/8074"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/aiohttp/PYSEC-2024-26.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/"},{"url":"https://github.com/advisories/GHSA-8qpw-xqxj-h4r2"}]}}},{"dismissedAt":null,"createdAt":"2024-01-30T00:07:40Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"aiohttp"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-5h86-8mv2-jq9f"},{"type":"CVE","value":"CVE-2024-23334"}],"references":[{"url":"https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5h86-8mv2-jq9f"},{"url":"https://github.com/aio-libs/aiohttp/pull/8079/files"},{"url":"https://github.com/aio-libs/aiohttp/commit/1c335944d6a8b1298baf179b7c0b3069f10c514b"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-23334"},{"url":"https://github.com/aio-libs/aiohttp/pull/8079"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/aiohttp/PYSEC-2024-24.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/"},{"url":"https://github.com/advisories/GHSA-5h86-8mv2-jq9f"}]}}},{"dismissedAt":null,"createdAt":"2024-02-06T03:07:55Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"cryptography"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-3ww4-gg4f-jr7f"},{"type":"CVE","value":"CVE-2023-50782"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-50782"},{"url":"https://access.redhat.com/security/cve/CVE-2023-50782"},{"url":"https://bugzilla.redhat.com/show_bug.cgi?id=2254432"},{"url":"https://github.com/pyca/cryptography/issues/9785"},{"url":"https://github.com/advisories/GHSA-3ww4-gg4f-jr7f"}]}}},{"dismissedAt":null,"createdAt":"2024-02-07T18:25:31Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-xxj9-f6rv-m3x4"},{"type":"CVE","value":"CVE-2024-24680"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-24680"},{"url":"https://docs.djangoproject.com/en/5.0/releases/security/"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/feb/06/security-releases/"},{"url":"https://github.com/django/django/commit/16a8fe18a3b81250f4fa57e3f93f0599dc4895bc"},{"url":"https://github.com/django/django/commit/55519d6cf8998fe4c8f5c8abffc2b10a7c3d14e9"},{"url":"https://github.com/django/django/commit/572ea07e84b38ea8de0551f4b4eda685d91d09d2"},{"url":"https://github.com/django/django/commit/c1171ffbd570db90ca206c30f8e2b9f691243820"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-28.yaml"},{"url":"https://github.com/advisories/GHSA-xxj9-f6rv-m3x4"}]}}}]},"grade":"D"}]}