{"totalCount":8,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/sparte","vulnerabilityAlerts":{"totalCount":8,"nodes":[{"dismissedAt":null,"createdAt":"2023-08-29T23:52:40Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jupyter-server"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-64x5-55rw-9974"},{"type":"CVE","value":"CVE-2023-40170"}],"references":[{"url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-64x5-55rw-9974"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-40170"},{"url":"https://github.com/jupyter-server/jupyter_server/commit/87a4927272819f0b1cae1afa4c8c86ee2da002fd"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2023-157.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XDKQAWQN6SQTOVACZNXYKEHWQXGG4DOF/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRP7DNZYVOIA4ZB3U3ZWKTFZEPYWNGCQ/"},{"url":"https://github.com/advisories/GHSA-64x5-55rw-9974"}]}}},{"dismissedAt":null,"createdAt":"2023-08-29T23:52:47Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jupyter-server"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-r726-vmfq-j9j3"},{"type":"CVE","value":"CVE-2023-39968"}],"references":[{"url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-r726-vmfq-j9j3"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-39968"},{"url":"https://github.com/jupyter-server/jupyter_server/commit/290362593b2ffb23c59f8114d76f77875de4b925"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2023-155.yaml"},{"url":"https://blog.xss.am/2023/08/cve-2023-39968-jupyter-token-leak"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRP7DNZYVOIA4ZB3U3ZWKTFZEPYWNGCQ"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XDKQAWQN6SQTOVACZNXYKEHWQXGG4DOF"},{"url":"https://github.com/advisories/GHSA-r726-vmfq-j9j3"}]}}},{"dismissedAt":null,"createdAt":"2023-12-05T18:26:07Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jupyter-server"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h56g-gq9v-vc8r"},{"type":"CVE","value":"CVE-2023-49080"}],"references":[{"url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-h56g-gq9v-vc8r"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-49080"},{"url":"https://github.com/jupyter-server/jupyter_server/commit/0056c3aa52cbb28b263a7a609ae5f17618b36652"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/62LO7PPIAMLIDEKUOORXLHKLGA6QPL77/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FG2JWZI5KPUYMDPS53AIFTZJWZD3IT6I/"},{"url":"https://github.com/advisories/GHSA-h56g-gq9v-vc8r"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:00:49Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qg2p-9jwr-mmqf"},{"type":"CVE","value":"CVE-2024-38875"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"},{"url":"https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"},{"url":"https://github.com/advisories/GHSA-qg2p-9jwr-mmqf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:01:31Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9jmf-237g-qf46"},{"type":"CVE","value":"CVE-2024-39330"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39330"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"},{"url":"https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"},{"url":"https://github.com/advisories/GHSA-9jmf-237g-qf46"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:01:45Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-x7q2-wr7g-xqmf"},{"type":"CVE","value":"CVE-2024-39329"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39329"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"},{"url":"https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"},{"url":"https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:03:00Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-f6f8-9mx6-9mx2"},{"type":"CVE","value":"CVE-2024-39614"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"},{"url":"https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"},{"url":"https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"}]}}},{"dismissedAt":null,"createdAt":"2024-07-15T14:14:57Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"axios"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-wf5p-g6vw-rhxx"},{"type":"CVE","value":"CVE-2023-45857"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-45857"},{"url":"https://github.com/axios/axios/issues/6006"},{"url":"https://github.com/axios/axios/issues/6022"},{"url":"https://github.com/axios/axios/pull/6028"},{"url":"https://github.com/axios/axios/commit/96ee232bd3ee4de2e657333d4d2191cd389e14d0"},{"url":"https://github.com/axios/axios/releases/tag/v1.6.0"},{"url":"https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459"},{"url":"https://github.com/axios/axios/pull/6091"},{"url":"https://github.com/axios/axios/commit/2755df562b9c194fba6d8b609a383443f6a6e967"},{"url":"https://github.com/axios/axios/releases/tag/v0.28.0"},{"url":"https://security.netapp.com/advisory/ntap-20240621-0006"},{"url":"https://github.com/advisories/GHSA-wf5p-g6vw-rhxx"}]}}}]},"grade":"D"}]}