{"totalCount":21,"grade":"E","repositories":[{"url":"https://github.com/MTES-MCT/apilos","vulnerabilityAlerts":{"totalCount":21,"nodes":[{"dismissedAt":null,"createdAt":"2024-03-18T20:56:56Z","securityVulnerability":{"severity":"LOW","package":{"name":"djangorestframework-simplejwt"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-5vcc-86wm-547q"},{"type":"CVE","value":"CVE-2024-22513"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-22513"},{"url":"https://github.com/dmdhrumilmistry/CVEs/tree/main/CVE-2024-22513"},{"url":"https://github.com/jazzband/djangorestframework-simplejwt/blob/c791e987332ed5e22a86428160d6372b1d85ffae/rest_framework_simplejwt/tokens.py#L281"},{"url":"https://github.com/advisories/GHSA-5vcc-86wm-547q"}]}}},{"dismissedAt":null,"createdAt":"2024-06-17T22:09:28Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"urllib3"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-34jh-p97f-mpxf"},{"type":"CVE","value":"CVE-2024-37891"}],"references":[{"url":"https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891"},{"url":"https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"},{"url":"https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"},{"url":"https://github.com/advisories/GHSA-34jh-p97f-mpxf"}]}}},{"dismissedAt":null,"createdAt":"2024-06-17T22:09:50Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"urllib3"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-34jh-p97f-mpxf"},{"type":"CVE","value":"CVE-2024-37891"}],"references":[{"url":"https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891"},{"url":"https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"},{"url":"https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"},{"url":"https://github.com/advisories/GHSA-34jh-p97f-mpxf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-06T00:22:41Z","securityVulnerability":{"severity":"LOW","package":{"name":"certifi"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-248v-346w-9cwc"},{"type":"CVE","value":"CVE-2024-39689"}],"references":[{"url":"https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"},{"url":"https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689"},{"url":"https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"},{"url":"https://github.com/advisories/GHSA-248v-346w-9cwc"}]}}},{"dismissedAt":null,"createdAt":"2024-07-06T00:23:11Z","securityVulnerability":{"severity":"LOW","package":{"name":"certifi"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-248v-346w-9cwc"},{"type":"CVE","value":"CVE-2024-39689"}],"references":[{"url":"https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"},{"url":"https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689"},{"url":"https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"},{"url":"https://github.com/advisories/GHSA-248v-346w-9cwc"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:02:17Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qg2p-9jwr-mmqf"},{"type":"CVE","value":"CVE-2024-38875"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"},{"url":"https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"},{"url":"https://github.com/advisories/GHSA-qg2p-9jwr-mmqf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:02:18Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qg2p-9jwr-mmqf"},{"type":"CVE","value":"CVE-2024-38875"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"},{"url":"https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"},{"url":"https://github.com/advisories/GHSA-qg2p-9jwr-mmqf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:02:53Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9jmf-237g-qf46"},{"type":"CVE","value":"CVE-2024-39330"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39330"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"},{"url":"https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"},{"url":"https://github.com/advisories/GHSA-9jmf-237g-qf46"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:02:53Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9jmf-237g-qf46"},{"type":"CVE","value":"CVE-2024-39330"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39330"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"},{"url":"https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"},{"url":"https://github.com/advisories/GHSA-9jmf-237g-qf46"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:03:19Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-x7q2-wr7g-xqmf"},{"type":"CVE","value":"CVE-2024-39329"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39329"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"},{"url":"https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"},{"url":"https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:03:19Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-x7q2-wr7g-xqmf"},{"type":"CVE","value":"CVE-2024-39329"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39329"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"},{"url":"https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"},{"url":"https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:05:31Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-f6f8-9mx6-9mx2"},{"type":"CVE","value":"CVE-2024-39614"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"},{"url":"https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"},{"url":"https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:05:32Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-f6f8-9mx6-9mx2"},{"type":"CVE","value":"CVE-2024-39614"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"},{"url":"https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"},{"url":"https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:19:15Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jh75-99hh-qvx9"},{"type":"CVE","value":"CVE-2024-41989"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41989"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/27900fe56f3d3cabb4aeb6ccb82f92bab29073a8"},{"url":"https://github.com/django/django/commit/fc76660f589ac07e45e9cd34ccb8087aeb11904b"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-67.yaml"},{"url":"https://github.com/advisories/GHSA-jh75-99hh-qvx9"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:19:15Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jh75-99hh-qvx9"},{"type":"CVE","value":"CVE-2024-41989"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41989"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/27900fe56f3d3cabb4aeb6ccb82f92bab29073a8"},{"url":"https://github.com/django/django/commit/fc76660f589ac07e45e9cd34ccb8087aeb11904b"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-67.yaml"},{"url":"https://github.com/advisories/GHSA-jh75-99hh-qvx9"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:19:26Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-795c-9xpc-xw6g"},{"type":"CVE","value":"CVE-2024-41990"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41990"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/7b7b909579c8311c140c89b8a9431bf537febf93"},{"url":"https://github.com/django/django/commit/d0a82e26a74940bf0c78204933c3bdd6a283eb88"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-68.yaml"},{"url":"https://github.com/advisories/GHSA-795c-9xpc-xw6g"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:19:26Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-795c-9xpc-xw6g"},{"type":"CVE","value":"CVE-2024-41990"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41990"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/7b7b909579c8311c140c89b8a9431bf537febf93"},{"url":"https://github.com/django/django/commit/d0a82e26a74940bf0c78204933c3bdd6a283eb88"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-68.yaml"},{"url":"https://github.com/advisories/GHSA-795c-9xpc-xw6g"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:20:08Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pv4p-cwwg-4rph"},{"type":"CVE","value":"CVE-2024-42005"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-42005"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/32ebcbf2e1fe3e5ba79a6554a167efce81f7422d"},{"url":"https://github.com/django/django/commit/f4af67b9b41e0f4c117a8741da3abbd1c869ab28"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-70.yaml"},{"url":"https://github.com/advisories/GHSA-pv4p-cwwg-4rph"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:20:08Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pv4p-cwwg-4rph"},{"type":"CVE","value":"CVE-2024-42005"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-42005"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/32ebcbf2e1fe3e5ba79a6554a167efce81f7422d"},{"url":"https://github.com/django/django/commit/f4af67b9b41e0f4c117a8741da3abbd1c869ab28"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-70.yaml"},{"url":"https://github.com/advisories/GHSA-pv4p-cwwg-4rph"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:20:18Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-r836-hh6v-rg5g"},{"type":"CVE","value":"CVE-2024-41991"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41991"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/523da8771bce321023f490f70d71a9e973ddc927"},{"url":"https://github.com/django/django/commit/efea1ef7e2190e3f77ca0651b5458297bc0f6a9f"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-69.yaml"},{"url":"https://github.com/advisories/GHSA-r836-hh6v-rg5g"}]}}}]},"grade":"E"}]}