{"totalCount":2,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/sparte","vulnerabilityAlerts":{"totalCount":2,"nodes":[{"dismissedAt":null,"createdAt":"2022-09-22T14:10:24Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django-celery-results"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-fvx8-v524-8579"},{"type":"CVE","value":"CVE-2020-17495"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2020-17495"},{"url":"https://github.com/celery/django-celery-results/issues/142"},{"url":"https://github.com/celery/django-celery-results/issues/154"},{"url":"https://github.com/celery/django-celery-results/pull/316"},{"url":"https://github.com/advisories/GHSA-fvx8-v524-8579"}]}}},{"dismissedAt":null,"createdAt":"2022-10-18T21:28:30Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"py"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w596-4wvx-j9j6"},{"type":"CVE","value":"CVE-2022-42969"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-42969"},{"url":"https://github.com/pytest-dev/py/issues/287"},{"url":"https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"},{"url":"https://github.com/pytest-dev/py/issues/288"},{"url":"https://github.com/pytest-dev/pytest/issues/10392"},{"url":"https://github.com/advisories/GHSA-w596-4wvx-j9j6"}]}}}]},"grade":"D"}]}