{"totalCount":10,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/sparte","vulnerabilityAlerts":{"totalCount":10,"nodes":[{"dismissedAt":null,"createdAt":"2022-01-06T22:32:04Z","securityVulnerability":{"severity":"HIGH","package":{"name":"celery"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-q4xr-rc97-m4xx"},{"type":"CVE","value":"CVE-2021-23727"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-23727"},{"url":"https://github.com/celery/celery/blob/master/Changelog.rst%23522"},{"url":"https://snyk.io/vuln/SNYK-PYTHON-CELERY-2314953"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SYXRGHWHD2WWMHBWCVD5ULVINPKNY3P5/"},{"url":"https://github.com/advisories/GHSA-q4xr-rc97-m4xx"}]}}},{"dismissedAt":null,"createdAt":"2022-01-20T13:03:40Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-v6rh-hp5x-86rv"},{"type":"CVE","value":"CVE-2021-44420"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-44420"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2021/dec/07/security-releases/"},{"url":"https://www.openwall.com/lists/oss-security/2021/12/07/1"},{"url":"https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6"},{"url":"https://docs.djangoproject.com/en/3.2/releases/security/"},{"url":"https://security.netapp.com/advisory/ntap-20211229-0006/"},{"url":"https://github.com/advisories/GHSA-v6rh-hp5x-86rv"}]}}},{"dismissedAt":null,"createdAt":"2022-01-20T13:03:41Z","securityVulnerability":{"severity":"HIGH","package":{"name":"celery"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-q4xr-rc97-m4xx"},{"type":"CVE","value":"CVE-2021-23727"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-23727"},{"url":"https://github.com/celery/celery/blob/master/Changelog.rst%23522"},{"url":"https://snyk.io/vuln/SNYK-PYTHON-CELERY-2314953"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SYXRGHWHD2WWMHBWCVD5ULVINPKNY3P5/"},{"url":"https://github.com/advisories/GHSA-q4xr-rc97-m4xx"}]}}},{"dismissedAt":null,"createdAt":"2022-01-20T13:03:41Z","securityVulnerability":{"severity":"LOW","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jrh2-hc4r-7jwx"},{"type":"CVE","value":"CVE-2021-45452"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45452"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://github.com/advisories/GHSA-jrh2-hc4r-7jwx"}]}}},{"dismissedAt":null,"createdAt":"2022-01-20T13:03:41Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-53qw-q765-4fww"},{"type":"CVE","value":"CVE-2021-45115"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45115"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://github.com/advisories/GHSA-53qw-q765-4fww"}]}}},{"dismissedAt":null,"createdAt":"2022-01-20T13:03:41Z","securityVulnerability":{"severity":"LOW","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8c5j-9r9f-c6w8"},{"type":"CVE","value":"CVE-2021-45116"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45116"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://github.com/advisories/GHSA-8c5j-9r9f-c6w8"}]}}},{"dismissedAt":null,"createdAt":"2022-01-20T13:03:41Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-v6rh-hp5x-86rv"},{"type":"CVE","value":"CVE-2021-44420"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-44420"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2021/dec/07/security-releases/"},{"url":"https://www.openwall.com/lists/oss-security/2021/12/07/1"},{"url":"https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6"},{"url":"https://docs.djangoproject.com/en/3.2/releases/security/"},{"url":"https://security.netapp.com/advisory/ntap-20211229-0006/"},{"url":"https://github.com/advisories/GHSA-v6rh-hp5x-86rv"}]}}},{"dismissedAt":null,"createdAt":"2022-01-20T13:03:41Z","securityVulnerability":{"severity":"LOW","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jrh2-hc4r-7jwx"},{"type":"CVE","value":"CVE-2021-45452"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45452"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://github.com/advisories/GHSA-jrh2-hc4r-7jwx"}]}}},{"dismissedAt":null,"createdAt":"2022-01-20T13:03:41Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-53qw-q765-4fww"},{"type":"CVE","value":"CVE-2021-45115"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45115"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://github.com/advisories/GHSA-53qw-q765-4fww"}]}}},{"dismissedAt":null,"createdAt":"2022-01-20T13:03:41Z","securityVulnerability":{"severity":"LOW","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8c5j-9r9f-c6w8"},{"type":"CVE","value":"CVE-2021-45116"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45116"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://github.com/advisories/GHSA-8c5j-9r9f-c6w8"}]}}}]},"grade":"D"}]}